configure: add --with-protobuf

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -32,6 +32,10 @@ openblas_check=include/openblas_config.h
 boost_path=
 boost_check=include/boost/test/unit_test.hpp
 
+# Protocol buffers library
+protobuf_path=
+protobuf_check=lib/libprotobuf.a
+
 have_kaldi=no
 kaldi_path=
 kaldi_check=src/kaldi.mk
@@ -89,6 +93,8 @@ default_mkls="CNTKCustomMKL"
 default_openblas=""
 
 default_boost="boost-1.60.0"
+
+default_protobuf="protobuf-3.1.0"
 
 # NOTE: Will get compilation errors with cuda-6.0
 default_cudas="cuda-7.5 cuda-7.0 cuda-6.5"
@@ -150,6 +156,11 @@ function find_openblas ()
 function find_boost ()
 {
     find_dir "$default_boost" "$boost_check"
+}
+
+function find_protobuf ()
+{
+    find_dir "$default_protobuf" "$protobuf_check"
 }
 
 function find_cuda ()
@@ -317,6 +328,7 @@ function show_help ()
     echo "  --with-libzip[=directory] $(show_default $(find_libzip))"
     echo "  --with-code-coverage[=(yes|no)] $(show_default ${default_use_code_coverage})"
     echo "  --with-boost[=directory] $(show_default $(find_boost))"
+    echo "  --with-protobuf[=directory] $(show_default $(find_protobuf))"
     echo "  --with-py-versions=(space-separated list of 34, 35)"
     echo "  --with-py34-path[=directory] $(show_default $(find_python 34))"
     echo "  --with-py35-path[=directory] $(show_default $(find_python 35))"
@@ -630,17 +642,37 @@ do
             then
                 boost_path=$(find_boost)
                 if test x$boost_path = x
-                then 
+                then
                     echo "Cannot find Boost directory"
                     echo "Please specify a value for --with-boost"
                     exit 1
                 fi
             else
                 if test $(check_dir $optarg $boost_check) = yes
-                then 
+                then
                     boost_path=$optarg
                 else
                     echo "Invalid Boost directory $optarg"
+                    exit 1
+                fi
+             fi
+             ;;
+        --with-protobuf*)
+            if test x$optarg = x
+            then
+                protobuf_path=$(find_protobuf)
+                if test x$protobuf_path = x
+                then
+                    echo "Cannot find Protobuf directory"
+                    echo "Please specify a value for --with-protobuf"
+                    exit 1
+                fi
+            else
+                if test $(check_dir $optarg $protobuf_check) = yes
+                then
+                    protobuf_path=$optarg
+                else
+                    echo "Invalid Protobuf directory $optarg"
                     exit 1
                 fi
              fi
@@ -897,6 +929,20 @@ then
     fi
 fi
 
+if test x$protobuf_path = x
+then
+    protobuf_path=$(find_protobuf)
+    if test x$protobuf_path = x
+    then
+        echo Cannot locate Protobuf library. See
+        echo   https://github.com/Microsoft/CNTK/wiki/Setup-CNTK-on-Linux#protobuf
+        echo for installation instructions.
+        exit 1
+    else
+        echo Found Protobuf at $protobuf_path
+    fi
+fi
+
 config=$build_top/Config.make
 echo Generating $config
 echo "#Configuration file for cntk" > $config
@@ -947,6 +993,9 @@ if test $enable_code_coverage = yes ; then
 fi
 if test x$boost_path != x; then
     echo BOOST_PATH=$boost_path >> $config
+fi
+if test x$protobuf_path != x; then
+    echo PROTOBUF_PATH=$protobuf_path >> $config
 fi
 
 # If we are not in the configure directory, generate a trampoline Makefile
